version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    command: gunicorn -w2 -b :8000 wsgi:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

